### PR TITLE
fix: Registration timeouts by removing Express contract test inputs

### PR DESCRIPTION
**Pull request by jormello**
*Description of changes:*
Removes secondary set of contract test inputs used for Express workflows. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by yuan-bwn — COMMENTED** [review]
Seems like github build has failed because of wrong param number in multiple methods. Is this expected?

**Comment by jormello** [comment]
Build failures are due to `cloudformation-cli-java-plugin` dependency releasing `2.0.6`. Will look into whether we can temporarily freeze the dependency at `2.0.5` which I've tested works, or whether we need to support the new version right away.

**Comment by jormello** [comment]
Addressed the build issues in this [PR](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-stepfunctions/pull/19). I will re-run the build check for this PR once the other PR is merged.

**Review by shivlaks — APPROVED** [review]
thanks for getting a fix together! provisional approval pending success in build step.

approved the related PR @jormello 
can you also include the motivation for excluding the tests in the CR description?

**Review by yuan-bwn — APPROVED** [review]

**Pull request merged**
